const actionType =  {
    GET_CLASSLIST: 'GET_CLASSLIST',
    GET_TEACHER_DETAILS: 'GET_TEACHER_DETAILS',
    GET_TYPEOF_EXAM: 'GET_TYPEOF_EXAM',
    GET_STUDENT_LIST: 'GET_STUDENT_LIST',
    UPDATE_PASSWORD: 'UPDATE_PASSWORD'
};
 
export default actionType;