const actionType =  {
    GET_CLASSLIST: 'GET_CLASSLIST',
    GET_TEACHER_DETAILS: 'GET_TEACHER_DETAILS',
    GET_TYPEOF_EXAM: 'GET_TYPEOF_EXAM',
    GET_STUDENT_LIST: 'GET_STUDENT_LIST',
    UPDATE_PASSWORD: 'UPDATE_PASSWORD',
    GET_STUDENT_MARKS_DATA: 'GET_STUDENT_MARKS_DATA',
    UPDATE_STUDENT_MARKS: 'UPDATE_STUDENT_MARKS',
    GET_AVG_MARKS: 'GET_AVG_MARKS',
    RESET_STUDENT_MARKS_DATA: 'RESET_STUDENT_MARKS_DATA',
    RESET_DATA: 'RESET_DATA',
    GET_MY_CLASS: 'GET_MY_CLASS',
    GET_MY_CLASS_MARKS: 'GET_MY_CLASS_MARKS',
    GET_MY_CLASS_SUBJECTS: 'GET_MY_CLASS_SUBJECTS',
    DISPLAY_STUDENT_SUMMARY: 'DISPLAY_STUDENT_SUMMARY',
    APPROVE_MARKS: 'APPROVE_MARKS',
    GET_APPROVED_STUDENTS_MARKS: 'GET_APPROVED_STUDENTS_MARKS',
    RESET_APPROVE_MARKS: 'RESET_APPROVE_MARKS',
    GET_CLASS_SUB_AVG: 'GET_CLASS_SUB_AVG',
    GET_LEAVE_APPROVALS: 'GET_LEAVE_APPROVALS',
    APPROVE_STUDENT_LEAVE: 'APPROVE_STUDENT_LEAVE',
    REJECT_STUDENT_LEAVE: 'REJECT_STUDENT_LEAVE'
};
 
export default actionType;