const actionType =  {
    GET_CLASSLIST: 'GET_CLASSLIST',
    GET_TEACHER_DETAILS: 'GET_TEACHER_DETAILS',
    GET_TYPEOF_EXAM: 'GET_TYPEOF_EXAM',
    GET_STUDENT_LIST: 'GET_STUDENT_LIST',
    UPDATE_PASSWORD: 'UPDATE_PASSWORD',
    GET_STUDENT_MARKS_DATA: 'GET_STUDENT_MARKS_DATA',
    UPDATE_STUDENT_MARKS: 'UPDATE_STUDENT_MARKS',
    GET_AVG_MARKS: 'GET_AVG_MARKS',
    RESET_STUDENT_MARKS_DATA: 'RESET_STUDENT_MARKS_DATA',
    RESET_DATA: 'RESET_DATA',
    GET_MY_CLASS: 'GET_MY_CLASS'
};
 
export default actionType;