const actionType =  {
    GET_TIME_TABLE_CLASSLIST: 'GET_TIME_TABLE_CLASSLIST',
    GET_TIME_TABLE_SUBJECTLIST: 'GET_TIME_TABLE_SUBJECTLIST',
    TIME_TABLE_UPDATE:'TIME_TABLE_UPDATE',
    RESET_SUBJECT_DATA: 'RESET_SUBJECT_DATA'
};
 
export default actionType;